# Banner file location.
banner:
      location: classpath:/banners/myapp.txt
       
# Mysql configuration
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-03.cleardb.net/heroku_38b30d1cf83f219?reconnect=true
    username: bf8ed3a0c31f07
    password: 6de5f261
  jpa:
    show-sql: true
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        

        
         
        